'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Partial Public Class MiConexion
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=MiConexion")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Overridable Property Ciudad() As DbSet(Of Ciudad)
    Public Overridable Property Persona() As DbSet(Of Tbl_Persona)
    Public Overridable Property sysdiagrams() As DbSet(Of sysdiagrams)

End Class
